# Generated by Django 5.0.1 on 2024-01-27 01:41

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('data', models.JSONField(null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('mail', models.BooleanField(default=False)),
                ('in_app', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reason', models.CharField(choices=[('forgot_password', 'Forgot Password'), ('activate_account', 'Activate Account'), ('authenticate_payment', 'Authenticate Payment')], default='activate_account', max_length=50)),
                ('code', models.CharField(max_length=128)),
                ('timeout', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='otp',
            constraint=models.UniqueConstraint(fields=('reason', 'user'), name='unique_reason_for_user'),
        ),
    ]
